version: '3.3'
services:
    front:
        build:
            context: ./front
            dockerfile: Dockerfile
        stdin_open: true
        ports:
            - '3000:3000'
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./:/presentation
            - /presentation/node_modules
        command: yarn start
        depends_on:
            - back
    back:
        build:
            context: ./back
            dockerfile: Dockerfile
        container_name: FPSMetricsBack
        environment:
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_DB: 'FPSMetrics'
        restart: always
        ports:
            - '3003:3000'
        volumes:
            - ./:/FPSMetricsBack
            - /FPSMetricsBack/node_modules/
            - /dbdata
        depends_on:
            - db
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_DB: 'FPSMetrics'
        volumes:
            - ./dbdata/pgdata:/var/lib/postgresql/data
            - ./dbdata/backups:/var/lib/postgresql
        ports:
            - '5433:5432'
